version: '3.8'
volumes:
  db_data:
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sakila
  app:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    depends_on:
      - db
    links:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - WAIT_HOST=db:3306
      - DB_DIALECT=mysql
      - DB_DATABASE=sakila

